#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

case "$1" in
  start)
    stat_busy "Starting tourenplaner-server"
    [ ! -f /var/run/daemons/tourenplanerd ] && /usr/bin/tourenplaner-server &>/dev/null &
    if [ $? -gt 0 ]; then
      stat_fail
    else
      sleep 1
      pgrep -of "/usr/share/java/tourenplaner/tourenplaner-server.jar" > /var/run/tourenplaner-server.pid
      add_daemon tourenplanerd
      stat_done
    fi
    ;;

  stop)
    stat_busy "Stopping tourenplaner-server"
    [ -f /var/run/tourenplaner-server.pid ] && kill `cat /var/run/tourenplaner-server.pid`
    if [ $? -gt 0 ]; then
      stat_fail
    else
      rm_daemon tourenplanerd
      stat_done
    fi
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"
esac
exit 0
