#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

killtree() {
    local _pid=$1
    for _child in $(ps -o pid --no-headers --ppid ${_pid}); do
        killtree ${_child}
    done
    kill ${_pid}
}

case "$1" in
  start)
    stat_busy "Starting tourenplaner-server"
    if [ ! -f /var/run/daemons/tourenplanerd ]
    then
	 /usr/bin/tourenplaner-server &> /var/log/tourenplanerd &
         TP_PID=$!
    fi
    if [ $? -gt 0 ]; then
      stat_fail
    else
      echo $TP_PID > /var/run/tourenplaner-server.pid
      add_daemon tourenplanerd
      stat_done
    fi
    ;;

  stop)
    stat_busy "Stopping tourenplaner-server"
    [ -f /var/run/tourenplaner-server.pid ] && killtree `cat /var/run/tourenplaner-server.pid` #&>/dev/null
    if [ $? -gt 0 ]; then
      #rm_daemon tourenplanerd
      stat_fail
    else
      rm_daemon tourenplanerd
      stat_done
    fi
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  force-stop)
    rm_daemon tourenplanerd
    rm /var/run/tourenplaner-server.pid
    pkill -u http -f "/usr/share/java/tourenplaner/tourenplaner-server.jar"
    sleep 2
    pkill -9 -u http -f "/usr/share/java/tourenplaner/tourenplaner-server.jar"
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"
esac
exit 0
